### ISSUE TITLE
Cotton Eye Joe

### ISSUE THREAD

**Issue by C8H8** [FRC2706/test#3]
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
He came to town like a midwinter storm
He rode through the fields, so handsome and strong
His eyes was his tools and his smile was his gun
But all he had come for was having some fun
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
He brought disaster wherever he went
The hearts of the girls was to Hell, broken, sent
They all ran away so nobody would know
And left only men 'cause of Cotton-Eye Joe
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?
If it hadn't been for Cotton-Eye Joe
I'd been married a long time ago
Where did you come from, where did you go?
Where did you come from, Cotton-Eye Joe?

**Comment by subspace-fractures-and-you** [comment]
<sup>ThAts<sup>mY<sub>FaVouRite</sup></sup></sub> <sup>S</sup>o<sup>N</sup>g

**Comment by GabbyGenereux** [comment]
I've never looked in depth at the lyrics for Cotton-Eyed Joe. #TheMoreYouKnow
