### ISSUE TITLE
This is my issue

### ISSUE THREAD

**Issue by georgetzavelas** [FRC2706/test#30]
### This is what I want to do
I am going to do the following
- [x] Thing 1
- [x] Thing 2

@greyingjay @FRC2706/autonomous 

**bold things**

[Go here](http://www.google.com)

![dont-do-elmo](https://user-images.githubusercontent.com/3611823/31747680-145deee8-b43c-11e7-83be-7f45c2070e60.gif)

**Comment by greyingjay** [comment]
Nooo! Poor Elmo!

**Comment by JAGMAN248** [comment]
Wow
