### ISSUE TITLE
JOIN THE SCOUTING REGIMENT

### ISSUE THREAD

**Issue by FilledWithDetermination** [FRC2706/test#47]
# Reasons to Join:
- You get no sleep
- You get to cry over picklists
- You will develop a hatred for spreadsheets
- Fun!!

@wakandacat @Crazycat200 @13evilcows @georgetzavelas

**Comment by Zinka010** [comment]
Fun on a bun

**Comment by Zinka010** [comment]
![image](https://user-images.githubusercontent.com/20603260/31747881-8730fd9c-b43d-11e7-951a-194d10a578a9.png)
