### ISSUE TITLE
{ Boring Issue Name }

### ISSUE THREAD

**Issue by TriShade** [FRC2706/test#48]
- [x] _obligatory_
- [x] **formatting**

I'm incapable of wit so enjoy some absurdity instead.

![k83idg6](https://user-images.githubusercontent.com/32915714/31747745-96e03754-b43c-11e7-9575-96191e0afa4a.gif)

Congratulations on not being known @eAUE

**Comment by JAGMAN248** [comment]
Oh you can edit, cool
